rm(list=ls())

library(tidyverse)
library(sjmisc)
library(readr)
library(dplyr)
library(lubridate)
library(tidyr)
library(readr)
library(skimr)
library(scales)
library(httr)
library(jsonlite)
library(janitor)
library(Matrix)
library(stringr)
library(data.table)
library(acs)
library(tidycensus)
library(tidygeocoder)
library(fs)
library(PredictABEL)
library(ggplot2)
library(tictoc)
library(forcats)

wd <- "/Users/ckim/Library/CloudStorage/Dropbox/Research/Research Assistance/Portland"
code_dir <- paste0(wd, "/code")
data_dir <- paste0(wd, "/SERVUS")
working_data_dir <- paste0(wd, "/working_data")

source(paste0(code_dir, "/geocoding_api.R"))
source(paste0(code_dir, "/setup_portland.R"))
source(paste0(code_dir, "/servus_exploration.R"))
source(paste0(code_dir, "/tidy_census_api.R"))
