WITH unique_census AS (
  SELECT DISTINCT 
    census_year,
    state_id,
    county_id,
    tract_id,
    block_group_id,
    total_house_holds,
    average_house_hold_size,
    average_house_hold_size_owner,
    average_house_hold_size_renter,
    educational_attainment_total,
    educational_attainment_no_schooling,
    educational_attainment_nursery_school,
    educational_attainment_kindergarten,
    educational_attainment_1st_grade,
    educational_attainment_2nd_grade,
    educational_attainment_3rd_grade,
    educational_attainment_4th_grade,
    educational_attainment_5th_grade,
    educational_attainment_6th_grade,
    educational_attainment_7th_grade,
    educational_attainment_8th_grade,
    educational_attainment_9th_grade,
    educational_attainment_10th_grade,
    educational_attainment_11th_grade,
    educational_attainment_12th_grade_no_diploma,
    educational_attainment_high_school_diploma,
    educational_attainment_ged_or_alternative,
    educational_attainment_some_college_less_than_1_year,
    educational_attainment_some_college_1_or_more_years_no_degree,
    educational_attainment_associates_degree,
    educational_attainment_bachelors_degree,
    educational_attainment_masters_degree,
    educational_attainment_professional_school_degree,
    educational_attainment_doctorate_degree,
    aggregate_house_hold_income,
    aggregate_house_hold_earnings,
    aggregate_house_hold_retirement_income,
    aggregate_house_hold_cash_assistance,
    median_house_hold_income,
    house_holds_with_under_18,
    house_holds_with_65_plus,
    house_holds_with_retirement_income,
    house_holds_with_ssi,
    house_holds_with_cash_assistance,
    house_holds_with_food_stamps,
    house_holds_in_poverty,
    employment_total,
    employed_total,
    unemployed_total,
    total_population_over_16,
    median_number_of_rooms,
    male_under_6_with_no_health_insurance,
    male_6_to_18_with_no_health_insurance,
    male_19_to_25_with_no_health_insurance,
    male_26_to_34_with_no_health_insurance,
    male_35_to_44_with_no_health_insurance,
    male_45_to_54_with_no_health_insurance,
    male_55_to_64_with_no_health_insurance,
    male_65_to_74_with_no_health_insurance,
    male_over_75_with_no_health_insurance,
    female_under_6_with_no_health_insurance,
    female_6_to_18_with_no_health_insurance,
    female_19_to_25_with_no_health_insurance,
    female_26_to_34_with_no_health_insurance,
    female_35_to_44_with_no_health_insurance,
    female_45_to_54_with_no_health_insurance,
    female_55_to_64_with_no_health_insurance,
    female_65_to_74_with_no_health_insurance,
    female_over_75_with_no_health_insurance,
    vehicles_owned_0,
    vehicles_owned_1,
    vehicles_owned_2,
    vehicles_owned_3,
    vehicles_owned_4,
    vehicles_owned_more_than_4,
    housing_cost_renter,
    housing_cost_owner,
    house_hold_renting,
    house_hold_owning,
    median_housing_market_value,
    median_age,
    population_includes_native_american,
    population_includes_hispanic,
    population_includes_asian,
    population_includes_pacific_islander,
    population_includes_black,
    population_includes_white,
    population_includes_other_race,
    male_age_under_5,
    male_age_5_to_9,
    male_age_10_to_14,
    male_age_15_to_17,
    male_age_18_to_19,
    male_age_20,
    male_age_21,
    male_age_22_to_24,
    male_age_25_to_29,
    male_age_30_to_34,
    male_age_35_to_39,
    male_age_40_to_44,
    male_age_45_to_49,
    male_age_50_to_54,
    male_age_55_to_59,
    male_age_60_to_61,
    male_age_62_to_64,
    male_age_65_to_66,
    male_age_67_to_69,
    male_age_70_to_74,
    male_age_75_to_79,
    male_age_80_to_84,
    male_age_over_85,
    female_age_under_5,
    female_age_5_to_9,
    female_age_10_to_14,
    female_age_15_to_17,
    female_age_18_to_19,
    female_age_20,
    female_age_21,
    female_age_22_to_24,
    female_age_25_to_29,
    female_age_30_to_34,
    female_age_35_to_39,
    female_age_40_to_44,
    female_age_45_to_49,
    female_age_50_to_54,
    female_age_55_to_59,
    female_age_60_to_61,
    female_age_62_to_64,
    female_age_65_to_66,
    female_age_67_to_69,
    female_age_70_to_74,
    female_age_75_to_79,
    female_age_80_to_84,
    female_age_over_85
  FROM census_data
),
aggregate_census AS (
  SELECT
    census_year,
    state_id,
    county_id,
    tract_id,
    block_group_id,
    total_house_holds,
    average_house_hold_size,
    average_house_hold_size_owner,
    average_house_hold_size_renter,
    median_age,
    COALESCE(ROUND(SAFE_DIVIDE(unemployed_total, unemployed_total+employed_total)*100, 2), 0) AS unemployment_rate,
    COALESCE(ROUND(SAFE_DIVIDE(employment_total, total_population_over_16)*100, 2), 0) AS percent_of_individuals_above_sixteen_in_labor_force,
    population_includes_native_american,
    population_includes_hispanic,
    population_includes_asian,
    population_includes_pacific_islander,
    population_includes_black,
    population_includes_white,
    population_includes_other_race,
    median_number_of_rooms,
    housing_cost_renter,
    housing_cost_owner,
    house_hold_renting,
    house_hold_owning,
    median_housing_market_value,
    aggregate_house_hold_income,
    aggregate_house_hold_earnings,
    aggregate_house_hold_retirement_income,
    aggregate_house_hold_cash_assistance,
    median_house_hold_income,
    house_holds_with_under_18,
    house_holds_with_65_plus,
    house_holds_with_retirement_income,
    house_holds_with_ssi,
    house_holds_with_cash_assistance,
    house_holds_with_food_stamps,
    house_holds_in_poverty,
    vehicles_owned_0,
    vehicles_owned_1,
    vehicles_owned_2,
    -- Age Groups
    IFNULL(male_age_under_5, 0) + IFNULL(female_age_under_5, 0) AS age_under_5,
    IFNULL(male_age_5_to_9, 0) + IFNULL(female_age_5_to_9, 0) AS age_5_to_9,
    IFNULL(male_age_10_to_14, 0) + IFNULL(female_age_10_to_14, 0) AS age_10_to_14,
    IFNULL(male_age_15_to_17, 0) + IFNULL(male_age_18_to_19, 0) + IFNULL(female_age_15_to_17, 0) + IFNULL(female_age_18_to_19, 0) AS age_15_to_19,
    IFNULL(male_age_20, 0) + IFNULL(male_age_21, 0) + IFNULL(male_age_22_to_24, 0) + IFNULL(female_age_20, 0) + IFNULL(female_age_21, 0) + IFNULL(female_age_22_to_24, 0) AS age_20_to_24,
    IFNULL(male_age_25_to_29, 0) + IFNULL(male_age_30_to_34, 0) + IFNULL(female_age_25_to_29, 0) + IFNULL(female_age_30_to_34, 0) AS age_25_to_34,
    IFNULL(male_age_35_to_39, 0) + IFNULL(male_age_40_to_44, 0) + IFNULL(female_age_35_to_39, 0) + IFNULL(female_age_40_to_44, 0) AS age_35_to_44,
    IFNULL(male_age_45_to_49, 0) + IFNULL(male_age_50_to_54, 0) + IFNULL(female_age_45_to_49, 0) + IFNULL(female_age_50_to_54, 0) AS age_45_to_54,
    IFNULL(male_age_55_to_59, 0) + IFNULL(female_age_55_to_59, 0) AS age_55_to_59,
    IFNULL(male_age_60_to_61, 0) + IFNULL(male_age_62_to_64, 0) + IFNULL(female_age_60_to_61, 0) + IFNULL(female_age_62_to_64, 0) AS age_60_to_64,
    IFNULL(male_age_65_to_66, 0) + IFNULL(male_age_67_to_69, 0) + IFNULL(male_age_70_to_74, 0) + IFNULL(female_age_65_to_66, 0) + IFNULL(female_age_67_to_69, 0) + IFNULL(female_age_70_to_74, 0) AS age_65_to_74,
    IFNULL(male_age_75_to_79, 0) + IFNULL(male_age_80_to_84, 0) + IFNULL(female_age_75_to_79, 0) + IFNULL(female_age_80_to_84, 0) AS age_75_to_84,
    IFNULL(male_age_over_85, 0) + IFNULL(female_age_over_85, 0) AS age_over_85,
    -- Male total
    IFNULL(male_age_under_5, 0) + IFNULL(male_age_5_to_9, 0) + IFNULL(male_age_10_to_14, 0) + IFNULL(male_age_15_to_17, 0) + IFNULL(male_age_18_to_19, 0) + 
    IFNULL(male_age_20, 0) + IFNULL(male_age_21, 0) + IFNULL(male_age_22_to_24, 0) + IFNULL(male_age_25_to_29, 0) + 
    IFNULL(male_age_30_to_34, 0) + IFNULL(male_age_35_to_39, 0) +
    IFNULL(male_age_40_to_44, 0) + IFNULL(male_age_45_to_49, 0) + 
    IFNULL(male_age_50_to_54, 0) + IFNULL(male_age_55_to_59, 0) + 
    IFNULL(male_age_60_to_61, 0) + IFNULL(male_age_62_to_64, 0) + IFNULL(male_age_65_to_66, 0) + IFNULL(male_age_67_to_69, 0) + 
    IFNULL(male_age_70_to_74, 0) + IFNULL(male_age_75_to_79, 0) + 
    IFNULL(male_age_80_to_84, 0) + IFNULL(male_age_over_85, 0) AS male_age_total,
    -- Female total
    IFNULL(female_age_under_5, 0) + IFNULL(female_age_5_to_9, 0) + IFNULL(female_age_10_to_14, 0) + IFNULL(female_age_15_to_17, 0) + IFNULL(female_age_18_to_19, 0) + 
    IFNULL(female_age_20, 0) + IFNULL(female_age_21, 0) + IFNULL(female_age_22_to_24, 0) + IFNULL(female_age_25_to_29, 0) + 
    IFNULL(female_age_30_to_34, 0) + IFNULL(female_age_35_to_39, 0) + 
    IFNULL(female_age_40_to_44, 0) + IFNULL(female_age_45_to_49, 0) + 
    IFNULL(female_age_50_to_54, 0) + IFNULL(female_age_55_to_59, 0) + 
    IFNULL(female_age_60_to_61, 0) + IFNULL(female_age_62_to_64, 0) + IFNULL(female_age_65_to_66, 0) + IFNULL(female_age_67_to_69, 0) + 
    IFNULL(female_age_70_to_74, 0) + IFNULL(female_age_75_to_79, 0) + 
    IFNULL(female_age_80_to_84, 0) + IFNULL(female_age_over_85, 0) AS female_age_total,
    -- Education Groups
    IFNULL(educational_attainment_no_schooling, 0) + IFNULL(educational_attainment_nursery_school, 0) + IFNULL(educational_attainment_kindergarten, 0) + 
    IFNULL(educational_attainment_1st_grade, 0) + IFNULL(educational_attainment_2nd_grade, 0) + IFNULL(educational_attainment_3rd_grade, 0) + 
    IFNULL(educational_attainment_4th_grade, 0) + IFNULL(educational_attainment_5th_grade, 0) + IFNULL(educational_attainment_6th_grade, 0) + 
    IFNULL(educational_attainment_7th_grade, 0) + IFNULL(educational_attainment_8th_grade, 0) + IFNULL(educational_attainment_9th_grade, 0) + 
    IFNULL(educational_attainment_10th_grade, 0) + IFNULL(educational_attainment_11th_grade, 0) + IFNULL(educational_attainment_12th_grade_no_diploma, 0) AS educational_attainment_no_diploma,
    IFNULL(educational_attainment_high_school_diploma, 0) + IFNULL(educational_attainment_ged_or_alternative, 0) + 
    IFNULL(educational_attainment_some_college_less_than_1_year, 0) + IFNULL(educational_attainment_some_college_1_or_more_years_no_degree, 0) AS educational_attainment_diploma,
    IFNULL(educational_attainment_associates_degree, 0) AS educational_attainment_associates_degree,
    IFNULL(educational_attainment_bachelors_degree, 0) AS educational_attainment_bachelors_degree,
    IFNULL(educational_attainment_masters_degree, 0) + IFNULL(educational_attainment_professional_school_degree, 0) + IFNULL(educational_attainment_doctorate_degree, 0) AS educational_attainment_post_bachelor,
    -- Vehicle Ownership
    IFNULL(vehicles_owned_3, 0) + IFNULL(vehicles_owned_4, 0) + IFNULL(vehicles_owned_more_than_4, 0) AS vehicles_owned_more_than_3,
    IFNULL(vehicles_owned_0, 0) + IFNULL(vehicles_owned_1, 0) + IFNULL(vehicles_owned_2, 0) + IFNULL(vehicles_owned_3, 0) + IFNULL(vehicles_owned_4, 0) + IFNULL(vehicles_owned_more_than_4, 0) AS vehicles_owned_total,
    -- Population
    IFNULL(population_includes_native_american, 0) + IFNULL(population_includes_hispanic, 0) + IFNULL(population_includes_asian, 0) + 
    IFNULL(population_includes_pacific_islander, 0) + IFNULL(population_includes_black, 0) + IFNULL(population_includes_white, 0) + IFNULL(population_includes_other_race, 0) AS total_population,
    IFNULL(male_under_6_with_no_health_insurance, 0) +
    IFNULL(male_6_to_18_with_no_health_insurance, 0) +
    IFNULL(male_19_to_25_with_no_health_insurance, 0) +
    IFNULL(male_26_to_34_with_no_health_insurance, 0) +
    IFNULL(male_35_to_44_with_no_health_insurance, 0) +
    IFNULL(male_45_to_54_with_no_health_insurance, 0) +
    IFNULL(male_55_to_64_with_no_health_insurance, 0) +
    IFNULL(male_65_to_74_with_no_health_insurance, 0) +
    IFNULL(male_over_75_with_no_health_insurance, 0) +
    IFNULL(female_under_6_with_no_health_insurance, 0) +
    IFNULL(female_6_to_18_with_no_health_insurance, 0) +
    IFNULL(female_19_to_25_with_no_health_insurance, 0) +
    IFNULL(female_26_to_34_with_no_health_insurance, 0) +
    IFNULL(female_35_to_44_with_no_health_insurance, 0) +
    IFNULL(female_45_to_54_with_no_health_insurance, 0) +
    IFNULL(female_55_to_64_with_no_health_insurance, 0) +
    IFNULL(female_65_to_74_with_no_health_insurance, 0) +
    IFNULL(female_over_75_with_no_health_insurance, 0) AS population_with_no_health_insurance
  FROM unique_census
)
SELECT
  census_year,
  state_id,
  county_id,
  tract_id,
  block_group_id,
  -- Aggregated columns
  ROUND(SAFE_DIVIDE(age_under_5, (male_age_total + female_age_total)) * 100, 2) AS percent_age_under_5,
  ROUND(SAFE_DIVIDE(age_5_to_9, (male_age_total + female_age_total)) * 100, 2) AS percent_age_5_to_9,
  ROUND(SAFE_DIVIDE(age_10_to_14, (male_age_total + female_age_total)) * 100, 2) AS percent_age_10_to_14,
  ROUND(SAFE_DIVIDE(age_15_to_19, (male_age_total + female_age_total)) * 100, 2) AS percent_age_15_to_19,
  ROUND(SAFE_DIVIDE(age_20_to_24, (male_age_total + female_age_total)) * 100, 2) AS percent_age_20_to_24,
  ROUND(SAFE_DIVIDE(age_25_to_34, (male_age_total + female_age_total)) * 100, 2) AS percent_age_25_to_34,
  ROUND(SAFE_DIVIDE(age_35_to_44, (male_age_total + female_age_total)) * 100, 2) AS percent_age_35_to_44,
  ROUND(SAFE_DIVIDE(age_45_to_54, (male_age_total + female_age_total)) * 100, 2) AS percent_age_45_to_54,
  ROUND(SAFE_DIVIDE(age_55_to_59, (male_age_total + female_age_total)) * 100, 2) AS percent_age_55_to_59,
  ROUND(SAFE_DIVIDE(age_60_to_64, (male_age_total + female_age_total)) * 100, 2) AS percent_age_60_to_64,
  ROUND(SAFE_DIVIDE(age_65_to_74, (male_age_total + female_age_total)) * 100, 2) AS percent_age_65_to_74,
  ROUND(SAFE_DIVIDE(age_75_to_84, (male_age_total + female_age_total)) * 100, 2) AS percent_age_75_to_84,
  ROUND(SAFE_DIVIDE(age_over_85, (male_age_total + female_age_total)) * 100, 2) AS percent_age_over_85,
  COALESCE(ROUND(SAFE_DIVIDE(male_age_total, female_age_total), 2), 0) AS male_to_female_ratio,
  educational_attainment_no_diploma,
  educational_attainment_diploma,
  educational_attainment_associates_degree,
  educational_attainment_bachelors_degree,
  educational_attainment_post_bachelor,
  ROUND(SAFE_DIVIDE(IFNULL(vehicles_owned_0, 0), vehicles_owned_total)) AS percent_vehicles_owned_0,
  ROUND(SAFE_DIVIDE(IFNULL(vehicles_owned_1, 0), vehicles_owned_total)) AS percent_vehicles_owned_1,
  ROUND(SAFE_DIVIDE(IFNULL(vehicles_owned_2, 0), vehicles_owned_total)) AS percent_vehicles_owned_2,
  ROUND(SAFE_DIVIDE(vehicles_owned_more_than_3, vehicles_owned_total)) AS percent_vehicles_owned_more_than_3,
  -- Non-aggregated columns
  total_house_holds,
  average_house_hold_size,
  average_house_hold_size_owner,
  average_house_hold_size_renter,
  median_age,
  unemployment_rate AS unemployment_rate_in_labor_force,
  percent_of_individuals_above_sixteen_in_labor_force,
  ROUND(SAFE_DIVIDE(population_with_no_health_insurance, total_population) * 100, 2) AS percent_of_population_with_no_health_insurance,
  COALESCE(ROUND(SAFE_DIVIDE(population_includes_native_american,total_population)*100, 2), 0) AS percent_of_population_includes_native_american,
  COALESCE(ROUND(SAFE_DIVIDE(population_includes_hispanic,total_population)*100, 2), 0) AS percent_of_population_includes_hispanic,
  COALESCE(ROUND(SAFE_DIVIDE(population_includes_asian,total_population)*100, 2), 0) AS percent_of_population_includes_asian,
  COALESCE(ROUND(SAFE_DIVIDE(population_includes_pacific_islander,total_population)*100, 2), 0) AS percent_of_population_includes_pacific_islander,
  COALESCE(ROUND(SAFE_DIVIDE(population_includes_black,total_population)*100, 2), 0) AS percent_of_population_includes_black,
  COALESCE(ROUND(SAFE_DIVIDE(population_includes_white,total_population)*100, 2), 0) AS percent_of_population_includes_white,
  COALESCE(ROUND(SAFE_DIVIDE(population_includes_other_race,total_population)*100, 2), 0) AS percent_of_population_includes_other_race,
  median_number_of_rooms,
  housing_cost_renter,
  housing_cost_owner,
  COALESCE(ROUND(SAFE_DIVIDE(house_hold_renting,house_hold_renting+house_hold_owning)*100, 2), 0) AS percent_of_house_hold_renting,
  COALESCE(ROUND(SAFE_DIVIDE(house_hold_owning,house_hold_renting+house_hold_owning)*100, 2), 0) AS percent_of_house_hold_owning,
  median_housing_market_value,
  COALESCE(ROUND(SAFE_DIVIDE(aggregate_house_hold_income,total_house_holds), 2), 0) AS average_house_hold_income,
  COALESCE(ROUND(SAFE_DIVIDE(aggregate_house_hold_earnings,total_house_holds), 2), 0) AS average_house_hold_earnings,
  COALESCE(ROUND(SAFE_DIVIDE(aggregate_house_hold_retirement_income,total_house_holds), 2), 0) AS average_house_hold_retirement_income,
  COALESCE(ROUND(SAFE_DIVIDE(aggregate_house_hold_cash_assistance,total_house_holds), 2), 0) AS average_house_hold_cash_assistance,
  median_house_hold_income,
  COALESCE(ROUND(SAFE_DIVIDE(house_holds_in_poverty,total_house_holds)*100, 2), 0) AS percent_of_house_holds_in_poverty,
  COALESCE(ROUND(SAFE_DIVIDE(house_holds_with_under_18,total_house_holds)*100, 2), 0) AS percent_of_house_holds_with_under_18,
  COALESCE(ROUND(SAFE_DIVIDE(house_holds_with_65_plus,total_house_holds)*100, 2), 0) AS percent_of_house_holds_with_65_plus,
  COALESCE(ROUND(SAFE_DIVIDE(house_holds_with_retirement_income,total_house_holds)*100, 2), 0) AS percent_of_house_holds_with_retirement_income,
  COALESCE(ROUND(SAFE_DIVIDE(house_holds_with_ssi,total_house_holds)*100, 2), 0) AS percent_of_house_holds_with_ssi,
  COALESCE(ROUND(SAFE_DIVIDE(house_holds_with_cash_assistance,total_house_holds)*100, 2), 0) AS percent_of_house_holds_with_cash_assistance,
  COALESCE(ROUND(SAFE_DIVIDE(house_holds_with_food_stamps,total_house_holds)*100, 2), 0) AS percent_of_house_holds_with_food_stamps
FROM aggregate_census;